### ISSUE TITLE
Display name doesn't update on the main list

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/financial-selector#111]
###How it currently works
When you change the name of a display in apps it doesn't update on the main list but it will update in the breadcrumb

###How it should work
When you change the name of a display in apps it should update everywhere in the financial selector

https://drive.google.com/file/d/0B-WhEeWXfRbgb2xpcWFWbk84Ym8/view

**Comment by rodrigopavezi** [comment]
@sheadarlison this has been fixed https://github.com/Rise-Vision/financial-selector/pull/112. Let me know if you find any problem. cheers
