### ISSUE TITLE
Last Financial Instrument doesn't show as being removed

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/financial-selector#95]
### Steps to reproduce
Create a new list in the Financial Selector and add some instruments to it.
Using the Actions dropdown remove each instrument.
The last remaining instrument looks like it cannot be removed, but if you navigate away from the page and come back it is gone.

### What should happen
All instruments should be visibly removed from the list

### What actually happens
The last remaining instrument remains in the list until you navigate away and come back to the page

**Comment by sheadarlison** [comment]
@pcsandford do you know if this was fixed? Thanks
